# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ded2a3e6d8151ac3c129032be11fafa3b66e9351276e1047eb82c5c9c79a315183d6c26a8b6ae8bcaf6e2d41f5676076fc156af6e6c5038a14eb52ebe578f4c8

test:
  secret_key_base: 43d40885372d9684779fca3e8adeb8d1cbbf66ee966dc626aa7dd627e72b1db2343b163bf1ad6e42273819fa7fe77e522ca51a1ba48978a525670bd845ca9708

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
